### ISSUE TITLE
Support transparent decompression of UPX'd binaries

### ISSUE THREAD

**Issue by tstromberg** [chainguard-dev/malcontent#197]
Similar to how we transparently decompress other archival formats, we should be able to run "upx -d" if a program appears to be compressed with UPX.

We should probably show the decompressed payload as if it existed "inside" the other one, so that the rule matches for both compressed and uncompressed payloads show up differently. For example:

```
# file
- HIGH: this file was compressed with UPX!

# file ∴ upx
- CRITICAL: it's malware!
```

If a UPX'd binary is encountered, but the `upx` utility is unavailable, an error message should be sent to stderr, saying something like:

`"upx" not in path, unable to decompress binary for further analysis`

**Comment by tstromberg** [comment]
Now that we have seen cases where folks (trino) are shipping UPX'd binaries, we should prioritize this. Without this feature, differential analysis is impossible against these binaries.

I don't think we will find a go library that will keep up with the changes in upx, so I would just shell out to upx if available. I would argue that in diff mode, we should error out if you try to diff a upx'd binary without upx installed. 

As far as behaviors go, I would scan the file twice: once with upx and once without. I could see arguments for presenting it as multiple files, but for simplicity of presentation, I think I would just concatenate the results into a single file rather than make it seem like two files.

**Comment by egibs** [comment]
`upx` can be installed via Homebrew: https://formulae.brew.sh/formula/upx#default

I think this is valuable work now that we have a pattern for determining files that use odd compression (zlib).
