### ISSUE TITLE
analyze no longer streams output as results are generated

### ISSUE THREAD

**Issue by tstromberg** [chainguard-dev/malcontent#489]
When scanning a large directory, such as `/usr`, malcontent no longer outputs the results for files as they complete: it appears to wait until the end. This makes for poor UX as malcontent may go minutes with no output.

I suspect this regression came from the multi-threading changes.

The `scan` command seems to have the same limitation.

**Comment by egibs** [comment]
Worked on this over the weekend and I'm close to a solution using priority queues.
