### ISSUE TITLE
Add `make reformat-rules` target

### ISSUE THREAD

**Issue by tstromberg** [chainguard-dev/malcontent#542]
Our YARA rule formatting is all over the place: mixed whitespace types and indentation everywhere. 

The only YARA formatter I've found that works well is https://github.com/VirusTotal/gyp - which I've previously used for rule rewrites here: https://github.com/chainguard-dev/yato/blob/fba28885a8743f0195064ff468043abe2996ed41/yato.go#L66

Maybe we can make a simple `cmd/yara-fmt` command-line shell around `gyp` that the rule re-uses.

**Comment by egibs** [comment]
Didn't see this issue before opening #546. 

`yara-x` recently add an `fmt` command and since `yara-x` is a standalone binary in addition to having API bindings, it's portable and easy to install in our `out/linters` directory.

**Comment by tstromberg** [comment]
I think this is effectively done by `make yara-x-fmt`
