### ISSUE TITLE
"--stats scan" gives misleading statistics (analyze is fine)

### ISSUE THREAD

**Issue by tstromberg** [chainguard-dev/malcontent#648]
When you use `--stats` with `scan`, you can't get an idea of your hit rate as HIGH+CRIT always totals 100%. My guess is that it's because we drop misses before stat generation.

For example:

```
📊 Statistics
---
Files Scanned   10781 (0 skipped)
Total Risks     10781
---
⚠️  Risk Level Percentage
---
Risk Level    Percentage Count/Total
4/CRIT            89.46% 9645/10781
3/HIGH            10.54% 1136/10781
---
Number of behaviors      15758
```

**Comment by egibs** [comment]
Yep, we return an empty file report in `report.Generate` when running a `scan`:
```go
if c.Scan && overallRiskScore < HIGH {
	return malcontent.FileReport{}, nil
}
```

I'll reason about a fix for this.
