### ISSUE TITLE
Add transparent decompression support for .rpm files

### ISSUE THREAD

**Issue by tstromberg** [chainguard-dev/malcontent#667]
This doesn't work yet for producing results:

```
go run ./cmd/mal/ analyze openssl-3.0.15-1.1.mga9.x86_64.rpm
🔎 Scanning "openssl-3.0.15-1.1.mga9.x86_64.rpm"
```

RPM's are renamed `cpio` files, AFAIK, so we made need to bring in an appropriate Go library.

https://github.com/chainguard-dev/malcontent/blob/25e8a865c09dfcfa327b06d6dc06dbfd98e04da6/pkg/action/archive.go#L23 is where I would start as far as implementing this feature.

**Comment by egibs** [comment]
I'll see about doing `.deb` files as well since I was trying to scan one earlier today.
