### ISSUE TITLE
Keeping updated?

### ISSUE THREAD

**Issue by DigiAngel** [chainguard-dev/malcontent#675]
How does one keep this updated?  Can't really git pull so...any pointers?  Thank you!

**Comment by tstromberg** [comment]
At the moment, there is no independent rule update mechanism: rules are released alongside the latest code releases.

In production, we use `cgr.dev/chainguard/malcontent:latest`, which is auto-updated after each malcontent release.

I've been putting off intra-release rule updates until I felt like things were stable enough to warrant the added complexity, and I think we're mostly there. We'll still end up with a problem where the latest rules are eventually incompatible with old versions of malcontent, but we can figure out compatibility guarantees around that if it'd be helpful.

**Comment by DigiAngel** [comment]
Thank you...guess I can just do a reinstall when there's a new update :)
