### ISSUE TITLE
Mismatched SHA Values in required dependency pkg-config

### ISSUE THREAD

**Issue by jamie-albert** [chainguard-dev/malcontent#676]
The following [link listed in the readme](https://www.freedesktop.org/wiki/Software/pkg-config/) to download the requirement pkg-config has two paths to downloading the pkg-config-0.29.2.tar.gz. from the freedeskop page. When curling the url `http://pkgconfig.freedesktop.org/releases/pkg-config-0.29.2.tar.gz` from the path [The current release of pkg-config is version 0.29.2](https://lists.freedesktop.org/archives/pkg-config/2017-March/001084.html) on the freedesktop page, the SHA values differ from what is expected. However the package obtained by clicking the package version from the [/releases](https://pkgconfig.freedesktop.org/releases/) option from the same homepage ***does return the correct expected SHA value listed in the release notes*.**  The only difference between the URLs is the instance found in the release notes from going down the 0.29.2 link from the main page states a `http` prefix instead of the `https` found from copying the link off the package name on the releases page. Regardless of the url prefix it should be delivering the same contents. Issue has been filed in pkg-config project here https://gitlab.freedesktop.org/pkg-config/pkg-config/-/issues/84

**Comment by tstromberg** [comment]
That's a really interesting find! 

`pkg-config` itself seems to be either a very stable bit of software, or abandoned: the last release was 2017. I think the 

Apparently, `pkg-config` on my macOS machine uses `pkgconf` 2.3.0 via homebrew. `pkgconf` seems to be a drop-in replacement: https://gitea.treehouse.systems/ariadne/pkgconf

It looks like Fedora & Arch Linux also ship `pkgconf` now, Fedora uses some sort of compatibility shim: https://packages.fedoraproject.org/pkgs/pkgconf/pkgconf-pkg-config/

In my experience, you rarely have to manually install this dependency, as installing the yara-dev libraries will generally require it.

I'll send a PR to update the README.md.
